In [532]:
import numpy as np

In [533]:
a = np.array([10, 20, 30, 35])
b = np.array([[1, 2, 7], [10, 35, 44]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [534]:
type(a)

numpy.ndarray

In [535]:
type(b)

numpy.ndarray

In [536]:
type(c)

numpy.ndarray

In [537]:
a.shape

(4,)

In [538]:
b.shape

(2, 3)

In [539]:
c.shape

(3, 3)

In [540]:
a

array([10, 20, 30, 35])

In [541]:
b

array([[ 1,  2,  7],
       [10, 35, 44]])

In [542]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [543]:
np.zeros((2, 10, 10)) #Трехмерный масив из нулей, размером 10 на 10

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [544]:
np.ones((3, 11, 11)) #Четырёхмерный  массив из единиц, размером 3 на 11 на 11

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1

In [545]:
np.eye(11) #Единичная матрица

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [546]:
np.empty((3, 4)) #Пустой массив (Мусорный бак)

array([[ 3.,  3., -2., -5.],
       [ 1., -5., -1., -4.],
       [ 5.,  5.,  0.,  0.]])

In [547]:
np.empty((2, 1))

array([[0.e+000],
       [1.e-323]])

In [548]:
d = np.arange(11, 111, 11)
e = np.arange(-11, -111, -11)
f = np.arange(11111, -11111, -1)

In [549]:
d

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110])

In [550]:
np.set_printoptions(threshold = 1000, precision = 0) #Параметры по умолчанию

In [551]:
print("Массив d: ", d, "\nМассив e: ", e, "\nМассив f: ", f)

Массив d:  [ 11  22  33  44  55  66  77  88  99 110] 
Массив e:  [ -11  -22  -33  -44  -55  -66  -77  -88  -99 -110] 
Массив f:  [ 11111  11110  11109 ... -11108 -11109 -11110]


In [552]:
np.set_printoptions(threshold = 100000, precision = 5) #Выводит до 100 тысяч чисел, 5 знаков после запятой

In [553]:
print("Массив f: ", f)

Массив f:  [ 11111  11110  11109  11108  11107  11106  11105  11104  11103  11102
  11101  11100  11099  11098  11097  11096  11095  11094  11093  11092
  11091  11090  11089  11088  11087  11086  11085  11084  11083  11082
  11081  11080  11079  11078  11077  11076  11075  11074  11073  11072
  11071  11070  11069  11068  11067  11066  11065  11064  11063  11062
  11061  11060  11059  11058  11057  11056  11055  11054  11053  11052
  11051  11050  11049  11048  11047  11046  11045  11044  11043  11042
  11041  11040  11039  11038  11037  11036  11035  11034  11033  11032
  11031  11030  11029  11028  11027  11026  11025  11024  11023  11022
  11021  11020  11019  11018  11017  11016  11015  11014  11013  11012
  11011  11010  11009  11008  11007  11006  11005  11004  11003  11002
  11001  11000  10999  10998  10997  10996  10995  10994  10993  10992
  10991  10990  10989  10988  10987  10986  10985  10984  10983  10982
  10981  10980  10979  10978  10977  10976  10975  10974  10973  1

In [554]:
g = np.array([11, 34, 54, 69])

In [555]:
t=a+g
t

array([ 21,  54,  84, 104])

In [556]:
r = np.array(4)

In [557]:
t - r

array([ 17,  50,  80, 100])

In [558]:
r * g

array([ 44, 136, 216, 276])

In [559]:
p = g / a
p

array([1.1    , 1.7    , 1.8    , 1.97143])

In [560]:
t ** g

array([    350277500542221, 2585850567397998592,                   0,
                         0])

In [561]:
i = np.array([0, 1, 0, 1])

In [562]:
p / i

C:\Users\imagi\AppData\Local\Temp\ipykernel_19008\3906709704.py:1: RuntimeWarning: divide by zero encountered in divide
  p / i


array([    inf, 1.7    ,     inf, 1.97143])

In [563]:
k = np.array([np.inf, np.inf, np.inf, np.inf])
k

array([inf, inf, inf, inf])

In [564]:
k - i

array([inf, inf, inf, inf])

In [565]:
q = np.array([1, 45, 90, 60, 5, 9, 8, 10, 38, 69, 11, 55])
np.cos(q)

array([ 0.5403 ,  0.52532, -0.44807, -0.95241,  0.28366, -0.91113,
       -0.1455 , -0.83907,  0.95507,  0.99339,  0.00443,  0.02213])

In [566]:
p = 5 * np.cos(q)
p

array([ 2.70151,  2.62661, -2.24037, -4.76206,  1.41831, -4.55565,
       -0.7275 , -4.19536,  4.77537,  4.96695,  0.02213,  0.11063])

In [567]:
np.round(p, 0)

array([ 3.,  3., -2., -5.,  1., -5., -1., -4.,  5.,  5.,  0.,  0.])

In [568]:
np.sum(p) #Суммирование всех элементов массива между собой

np.float64(0.14057268427299874)

In [569]:
q.sum() #Другой способ

np.int64(401)

In [570]:
q.min() #Минимальный элемент массива

np.int64(1)

In [571]:
q.min(axis = 0) #Минимум по столбцам для каждой строки

np.int64(1)

In [572]:
p.max() #Максимальный элемент массива

np.float64(4.966951898611358)

In [573]:
p.max(axis = 0)

np.float64(4.966951898611358)

In [574]:
m = np.arange(11) ** 11
m

array([           0,            1,         2048,       177147,
            4194304,     48828125,    362797056,   1977326743,
         8589934592,  31381059609, 100000000000])

In [575]:
m[10]

np.int64(100000000000)

In [576]:
m[[1, 10]]

array([           1, 100000000000])

In [577]:
m[0] = 11
m[10] = 111111111111111111
m

array([                11,                  1,               2048,
                   177147,            4194304,           48828125,
                362797056,         1977326743,         8589934592,
              31381059609, 111111111111111111])

In [578]:
m[:: -1]

array([111111111111111111,        31381059609,         8589934592,
               1977326743,          362797056,           48828125,
                  4194304,             177147,               2048,
                        1,                 11])

In [579]:
m[-1]

np.int64(111111111111111111)

In [580]:
u = np.array([[10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43],
    [50, 51, 52, 53]]) #Создали двумерный массив
u

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43],
       [50, 51, 52, 53]])

In [581]:
u[3, 2] #Обращение к элементу на 4 строке в 3 столбце

np.int64(42)

In [582]:
u[[3, 1]]

array([[40, 41, 42, 43],
       [20, 21, 22, 23]])

In [583]:
u[[3,2],1]

array([41, 31])

In [584]:
u[[0, 1], [1, 1]]

array([11, 21])

In [585]:
u[1:2, 1:2]

array([[21]])

In [586]:
u[1:5, 1:5]

array([[21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53]])

In [587]:
u[1][3]

np.int64(23)

In [588]:
u[:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43],
       [50, 51, 52, 53]])

In [589]:
u[: 3] #Первые 3 строки массива

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [590]:
u[100] #блин ну как же так, ну что за байт Юрий Владимирович

IndexError: index 100 is out of bounds for axis 0 with size 5

In [ ]:
u[1:2][0]

In [591]:
y = np.ones((1, 5, 11, 1, 5, 11))
y

array([[[[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
           [1., 1.,

In [592]:
y[..., 2] #Опустили все предыдущие индексы

array([[[[[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]],

         [

In [593]:
h = np.array(([[1, 11, 111], [2, 22, 222]], [[1111, 11111, 111111], [2222, 22222, 222222]]))
h

array([[[     1,     11,    111],
        [     2,     22,    222]],

       [[  1111,  11111, 111111],
        [  2222,  22222, 222222]]])

In [594]:
h.shape

(2, 2, 3)

In [595]:
for row in h:
    print('\n', row)


 [[  1  11 111]
 [  2  22 222]]

 [[  1111  11111 111111]
 [  2222  22222 222222]]


In [596]:
h.flat

In [597]:
for el in h.flat:
    print(el)

1
11
111
2
22
222
1111
11111
111111
2222
22222
222222


In [598]:
h.ravel() #Делает массив плоским, но сам массив не изменяется

array([     1,     11,    111,      2,     22,    222,   1111,  11111,
       111111,   2222,  22222, 222222])

In [599]:
h.shape = (6, 2) #Изменение формы, сам массив изменяется
h

array([[     1,     11],
       [   111,      2],
       [    22,    222],
       [  1111,  11111],
       [111111,   2222],
       [ 22222, 222222]])

In [600]:
j = h.transpose() #Транспонирование, сам массив не изменяется
j

array([[     1,    111,     22,   1111, 111111,  22222],
       [    11,      2,    222,  11111,   2222, 222222]])

In [601]:
h.reshape((3, 4)) #Изменение формы, но сам массив не изменяется

array([[     1,     11,    111,      2],
       [    22,    222,   1111,  11111],
       [111111,   2222,  22222, 222222]])

In [602]:
b

array([[ 1,  2,  7],
       [10, 35, 44]])

In [603]:
s = np.array([[15, 16, 21], [17, 18, 111]])
s

array([[ 15,  16,  21],
       [ 17,  18, 111]])

In [604]:
np.vstack((b, s))

array([[  1,   2,   7],
       [ 10,  35,  44],
       [ 15,  16,  21],
       [ 17,  18, 111]])

In [605]:
np.hstack((b, s))

array([[  1,   2,   7,  15,  16,  21],
       [ 10,  35,  44,  17,  18, 111]])

In [606]:
np.column_stack((b, s))

array([[  1,   2,   7,  15,  16,  21],
       [ 10,  35,  44,  17,  18, 111]])

In [607]:
np.row_stack((b, s))

C:\Users\imagi\AppData\Local\Temp\ipykernel_19008\24741642.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((b, s))


array([[  1,   2,   7],
       [ 10,  35,  44],
       [ 15,  16,  21],
       [ 17,  18, 111]])

In [608]:
z = np.arange(12).reshape((2,6))
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [609]:
za, vo, zz = np.hsplit(z, 3) #Разбить на 3 части по столбцам
za

array([[0, 1],
       [6, 7]])

In [610]:
vo

array([[2, 3],
       [8, 9]])

In [611]:
zz

array([[ 4,  5],
       [10, 11]])

In [612]:
np.hsplit(z, (3, 4)) #Разрезать a после третьего и четвёртого столбца

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [613]:
np.vsplit(z, 2) #Разбить на 2 части по строкам

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [614]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [615]:
w = x
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [616]:
w is a #Проверим что это один и тот же объект

False

In [617]:
w is x #Проверим что это один и тот же объект

True

In [618]:
w.shape

(12,)

In [619]:
w.shape = (3, 4)
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [620]:
x.shape

(3, 4)

In [621]:
v = x.view()
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [622]:
v is x

False

In [623]:
v[1, 1] = 111111
x

array([[     0,      1,      2,      3],
       [     4, 111111,      6,      7],
       [     8,      9,     10,     11]])

In [624]:
j = x.copy()
j

array([[     0,      1,      2,      3],
       [     4, 111111,      6,      7],
       [     8,      9,     10,     11]])

In [625]:
j is x

False

In [626]:
j[2,2] = 1111
x

array([[     0,      1,      2,      3],
       [     4, 111111,      6,      7],
       [     8,      9,     10,     11]])

In [627]:
j

array([[     0,      1,      2,      3],
       [     4, 111111,      6,      7],
       [     8,      9,   1111,     11]])

In [628]:
np.mean(a)

np.float64(23.75)

In [629]:
np.mean(b)

np.float64(16.5)

In [630]:
np.mean(c)

np.float64(5.0)

In [631]:
np.mean(d)

np.float64(60.5)

In [632]:
np.mean(e)

np.float64(-60.5)

In [633]:
np.mean(f)

np.float64(0.5)

In [634]:
np.mean(g)

np.float64(42.0)

In [635]:
np.mean(p)

np.float64(0.011714390356083229)

In [636]:
np.mean(i)

np.float64(0.5)

In [637]:
np.mean(u)

np.float64(31.5)

In [638]:
np.mean(y)

np.float64(1.0)

In [639]:
np.mean(t)

np.float64(65.75)

In [640]:
np.mean(r)

np.float64(4.0)

In [641]:
np.mean(q)

np.float64(33.416666666666664)

In [642]:
np.mean(w)

np.float64(9264.333333333334)

In [643]:
np.mean(s)

np.float64(33.0)

In [644]:
np.mean(z)

np.float64(5.5)

In [645]:
np.mean(x)

np.float64(9264.333333333334)

In [646]:
np.mean(v)

np.float64(9264.333333333334)

In [647]:
np.mean(l)

np.float64(14.75)

In [648]:
np.mean(k)

np.float64(inf)

In [649]:
np.mean(m)

np.float64(1.0101013952311886e+16)

In [650]:
np.mean(h)

np.float64(30864.0)

In [651]:
print("ВСЁ")

ВСЁ
